### PR TITLE
Added Singly Linked list all Operations in cpp

### PR DESCRIPTION
**Pull request by chiragchandnani10**
image
#19 
This is my working code output. Thank you!
@Jayanti2919  Could you please merge this into the main folder?

### CODE REVIEW

**Review by Jayanti2919 — CHANGES_REQUESTED** [review]
Your entire main function is commented out. This code does not give any output.

Kindly make the necessary changes and attach screenshots of the working code output in your PR description

**Comment by chiragchandnani10** [comment]
@Jayanti2919 I have made the requested changes. Thank you! Could you merge my PR. Thank you!

**Comment by Jayanti2919** [comment]
@chiragchandnani10 can you put your files in an appropriate folder (create if required)? That would keep the repo's structure easier to read. Sorry for another review :(

**Comment by chiragchandnani10** [comment]
@Jayanti2919 Could you please help me in guiding me as to how can I add a new folder in the github repo within this PR, I am new to open source contributions, and your help would mean a lot. Thanks!

**Comment by chiragchandnani10** [comment]
@Jayanti2919 I added the whole folder into the PR. Please review it and merge it if possible. Thanks a lot! Got to learn a lot from this repo!

**Pull request merged**
