### PR TITLE
Added an AIML Project using python

### PR DESCRIPTION
**Pull request by Lordhacker756**
This project uses trained data to detect cars in real time either in a video source provided from a video or an external camera. Hope you like it!

### CODE REVIEW

**Comment by Jayanti2919** [comment]
Hi @Lordhacker756 ! It appears that you might have uploaded a zip folder which is not viewable on GitHub. Kindly look into the file type.

**Review by Jayanti2919 — CHANGES_REQUESTED** [review]
Unable to view files

**Comment by Lordhacker756** [comment]
@Jayanti2919 okay! lemme see

**Comment by Lordhacker756** [comment]
@Jayanti2919 I've added the project to a new folder. Please check it

**Pull request merged**
