### PR TITLE
added game in javascript language

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Jayanti2919** [comment]
Hi @VishalSharma8910 ! It appears that you may have uploaded a zip folder which is not viewable on GitHub. Kindly look into the file formatting

**Review by Jayanti2919 — CHANGES_REQUESTED** [review]
Change of file format required

**Comment by VishalSharma8910** [comment]
image
I am really sorry for the issue but if you can please help me with this issue.......as you can see in the screenshot there is a javascript project folder and in that, I have added a js project .....but I don't know why I am unable to see

**Comment by VishalSharma8910** [comment]
And ya there is no zip file I have added...if possible please guide me with this issue how to resolve it

**Comment by Jayanti2919** [comment]
This is how your code appears on GitHub:
image

The code cannot be viewed. Try uploading the specific folder that has your JS code. As visible in your screenshot, it should be "javascript project..."

**Pull request closed without merging**
