### PR TITLE
added guess number game in C++

### PR DESCRIPTION
**Pull request by AdityaMore7000**
Kindly add the hacktoberfest-accepted labels in this pull request while accepting.

Thank you for considering my contribution.

### CODE REVIEW

**Comment by Jayanti2919** [comment]
@AdityaMore7000 kindly add screenshot of the code working in your PR description

**Review by Jayanti2919 — CHANGES_REQUESTED** [review]
Screenshot of code working missing

**Comment by AdityaMore7000** [comment]
image

Kindly check this image

**Review by Jayanti2919 — CHANGES_REQUESTED** [review]
File not in appropriate folder

**Comment by AdityaMore7000** [comment]
Ok, I will submit it according to the instructions

**Pull request closed without merging**
